import os
import pandas as pd
import matplotlib.pyplot as plt

def fix_mojibake(value):
    """
    Fix common UTF-8 text that was incorrectly decoded
    as Latin-1/Windows-1252.
    """
    if not isinstance(value, str):
        return value

    try:
        return value.encode("latin1").decode("utf-8")
    except (UnicodeEncodeError, UnicodeDecodeError):
        return value

# ============================================================
# Configuration
# ============================================================

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
RESULTS_DIR = os.path.join(SCRIPT_DIR, "..", "results")

SAMPLE_SIZES = [1000, 3000, 5000]
COLUMNS = ["id", "title"]


# ============================================================
# Load histogram data
# ============================================================

def load_histogram_data(column, sample_size):
    """
    Load histogram bucket data generated by histogram.py.
    """
    filename = f"{column}_boundaries_{sample_size}.csv"
    filepath = os.path.join(RESULTS_DIR, filename)

    if not os.path.exists(filepath):
        raise FileNotFoundError(
            f"Histogram boundary file not found:\n{filepath}"
        )

    df = pd.read_csv(filepath)

    required_columns = [
        "bucket",
        "lower_boundary",
        "upper_boundary",
        "frequency"
    ]

    missing = [
        col for col in required_columns
        if col not in df.columns
    ]

    if missing:
        raise ValueError(
            f"{filename} is missing columns: {missing}"
        )

    return df


# ============================================================
# Create histogram plot
# ============================================================

def plot_histogram(column, sample_size):
    """
    Create a vertical bar plot.

    X-axis:
        Value boundaries

    Y-axis:
        Frequency
    """

    df = load_histogram_data(column, sample_size)

    # Create readable boundary labels.
    labels = []

    for _, row in df.iterrows():
        lower = fix_mojibake(str(row["lower_boundary"]))
        upper = fix_mojibake(str(row["upper_boundary"]))

        labels.append(
            f"{lower} – {upper}"
        )

    frequencies = df["frequency"].tolist()

    # --------------------------------------------------------
    # Figure size
    # --------------------------------------------------------

    plt.figure(
        figsize=(16, 12)
    )

    # --------------------------------------------------------
    # Vertical bar plot (Exchanged Axes)
    # --------------------------------------------------------

    plt.bar(
        labels,
        frequencies
    )

    # --------------------------------------------------------
    # Labels and title
    # --------------------------------------------------------

    plt.xlabel(
        "Value boundaries",
        fontsize=12
    )

    plt.ylabel(
        "Frequency",
        fontsize=12
    )

    plt.title(
        f"Serial Equi-Depth Histogram: "
        f"{column} ({sample_size} samples, 20 buckets)",
        fontsize=14
    )

    # --------------------------------------------------------
    # Tick formatting
    # --------------------------------------------------------

    # Rotate X-axis labels so they don't overlap vertically
    plt.xticks(
        rotation=45,
        ha="right",
        fontsize=8
    )

    plt.yticks(
        fontsize=10
    )

    # --------------------------------------------------------
    # Grid
    # --------------------------------------------------------

    # Grid along the Y-axis to read frequencies easily
    plt.grid(
        axis="y",
        linestyle="--",
        alpha=0.4
    )

    # --------------------------------------------------------
    # Layout
    # --------------------------------------------------------

    plt.tight_layout()

    # --------------------------------------------------------
    # Save
    # --------------------------------------------------------

    output_filename = (
        f"{column}_histogram_{sample_size}.png"
    )

    output_path = os.path.join(
        RESULTS_DIR,
        output_filename
    )

    plt.savefig(
        output_path,
        dpi=200,
        bbox_inches="tight"
    )

    plt.close()

    print(
        f"Generated: {output_filename}"
    )


# ============================================================
# Main
# ============================================================

def main():

    print("=" * 60)
    print("Histogram Plot Generator")
    print("=" * 60)

    print(f"Results directory: {os.path.abspath(RESULTS_DIR)}")
    print()

    for column in COLUMNS:

        for sample_size in SAMPLE_SIZES:

            print(
                f"Plotting {column}, "
                f"{sample_size} samples..."
            )

            plot_histogram(
                column,
                sample_size
            )

    print()
    print("=" * 60)
    print("ALL HISTOGRAM PLOTS GENERATED")
    print("=" * 60)


if __name__ == "__main__":
    main()